# Generated by Django 4.1 on 2022-10-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(blank=True, max_length=200)),
                ('affilation', models.CharField(blank=True, max_length=50)),
                ('domain', models.CharField(blank=True, max_length=150)),
                ('doi', models.URLField(blank=True)),
                ('month', models.CharField(blank=True, max_length=15)),
                ('year', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
