# Generated by Django 4.1 on 2022-10-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_researchpaper_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='year',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
