# Generated by Django 4.1 on 2022-10-29 08:26

import dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_researchpaper_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2000), dashboard.models.max_value_current_year], verbose_name='year'),
        ),
    ]
