# Generated by Django 4.1 on 2022-10-30 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_alter_researchpaper_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='authors',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desgignation', models.CharField(max_length=4, null=True)),
                ('scopus_id', models.CharField(max_length=50, null=True)),
                ('wos_id', models.CharField(max_length=50, null=True)),
                ('citation_count', models.CharField(max_length=50, null=True)),
                ('month_year', models.CharField(max_length=50, null=True)),
                ('dept', models.CharField(max_length=50, null=True)),
                ('orcid_id', models.CharField(max_length=50, null=True)),
                ('vidwan_id', models.CharField(max_length=50, null=True)),
                ('h_index', models.CharField(max_length=50, null=True)),
                ('i_index', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
