# Generated by Django 4.1 on 2022-10-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_researchpaper_authors_additionalinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalinfo',
            old_name='desgignation',
            new_name='designation',
        ),
    ]
