# Generated by Django 4.1 on 2022-12-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_additionalinfo_citation_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchpaper',
            name='affilation',
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='domain',
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='dept',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='faculty',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='name_of_conference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='name_of_journal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='scholar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='scopus_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='title_of_book',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='title_of_chapter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='title_of_paper',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
