# Generated by Django 4.1 on 2023-01-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_researchpaper_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchpaper',
            old_name='scopus_id',
            new_name='index_db',
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='dept',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='designation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='h_index',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='i_index',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
