# Generated by Django 4.1 on 2023-01-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_additionalinfo_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
