# Generated by Django 4.1.2 on 2023-02-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_profile_citation_count_profile_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='outside_authors',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='faculty',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='name_of_conference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='name_of_journal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='scholar',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='student',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='title_of_book',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='title_of_chapter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='title_of_paper',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
