# Generated by Django 4.1.2 on 2023-02-08 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0019_researchpaper_outside_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='users_associated',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
