# Generated by Django 4.1.2 on 2023-02-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_researchpaper_users_associated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
